# Generated by Django 5.0.7 on 2024-07-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_reparacion', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('alta_eficiencia', models.BooleanField(default=False)),
                ('descripcion_problema', models.TextField()),
            ],
        ),
    ]
