# Generated by Django 5.0.7 on 2024-07-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELECTRI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_reparacion',
            field=models.CharField(max_length=50),
        ),
    ]
